import numpy as np
ar1=np.array([1,1,2,3,4,4,5,6,7,7,8])
print(np.unique(ar1))
print(np.unique(ar1,return_index=1))
print(np.unique(ar1,return_counts=1))
ar2d=np.array([[1,2,3,4],[4,5,6,7],[1,2,3,4]])
print()
print(np.unique(ar2d))
print(np.unique(ar2d,return_index=1))
print(np.unique(ar2d,return_counts=1))
print()
print(np.unique(ar2d,axis=0))
print(np.unique(ar2d,return_index=1,axis=0))
print(np.unique(ar2d,return_counts=1,axis=0))