import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 5, 100) 
fig, ax = plt.subplots(layout='constrained')
ax.plot(x, x, label='linear') 
ax.plot(x, x**2, label='quadratic') 
ax.plot(x, x**3, label='cubic')  
ax.set_xlabel('x axis') 
ax.set_ylabel('y axis')  
ax.set_title("constrained layout")  
ax.legend()  
print("done")

fig2, ax2 = plt.subplots(layout='tight')
ax2.plot(x, x, label='linear') 
ax2.plot(x, x**2, label='quadratic') 
ax2.plot(x, x**3, label='cubic')  
ax2.set_xlabel('x axis') 
ax2.set_ylabel('y axis')  
ax2.set_title("tight layout")  
ax2.legend()  
print("done")


fig3, ax3 = plt.subplots()
ax3.plot(x, x, label='linear') 
ax3.plot(x, x**2, label='quadratic') 
ax3.plot(x, x**3, label='cubic')  
ax3.set_xlabel('x axis') 
ax3.set_ylabel('y axis')  
ax3.set_title("default layout")  
ax3.legend()  
print("showing graphs")
plt.show()
print("done")
